[package]
name = "doxus-plugin-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true, optional = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, optional = true }
regex = { workspace = true }
lazy_static = "1.4"

[features]
default = ["native"]
native = ["dep:async-trait", "dep:tokio"]
